name: build

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

env:
  RUSTUP_TOOLCHAIN: 1.85
  TESTS_BTCRPCCONNECTION: "server=http://127.0.0.1:43782;ceiwHEbqWI83:DwubwWsoo3"
  TESTS_BTCNBXPLORERURL: "http://127.0.0.1:32838/"
  TESTS_POSTGRES: "User ID=postgres;Include Error Detail=true;Host=127.0.0.1;Port=39372;Database=btcpayserver"
  TESTS_EXPLORER_POSTGRES: "User ID=postgres;Include Error Detail=true;Host=127.0.0.1;Port=39372;Database=nbxplorer"
  TESTS_MAILPIT_HOST: "127.0.0.1"
  TESTS_MAILPIT_SMTP: "34219"
  TESTS_MAILPIT_HTTP: "34218"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Payjoin CI
        uses: ./.github/actions/prepare-ci-build

      - name: Run unit tests
        run: dotnet test "BTCPayServer.Plugins.Payjoin.Tests/BTCPayServer.Plugins.Payjoin.Tests.csproj" -c Release --no-build

  integration-tests:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Payjoin CI
        uses: ./.github/actions/prepare-ci-build

      - name: Set up BTCPay integration test environment
        uses: ./.github/actions/prepare-integration-test-env

      - name: Run basic integration tests
        run: dotnet test "BTCPayServer.Plugins.Payjoin.IntegrationTests/BTCPayServer.Plugins.Payjoin.IntegrationTests.csproj" -c Release --no-build --filter "FullyQualifiedName!~BTCPayServer.Plugins.Payjoin.IntegrationTests.PayjoinCliIntegrationTests"

      - name: Dump BTCPay integration test infrastructure logs on failure
        if: failure()
        run: docker compose -f btcpayserver/BTCPayServer.Tests/docker-compose.yml logs --no-color

      - name: Stop BTCPay integration test infrastructure
        if: always()
        run: docker compose -f btcpayserver/BTCPayServer.Tests/docker-compose.yml down -v

  payjoin-cli-integration-tests:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Payjoin CI
        uses: ./.github/actions/prepare-ci-build

      - name: Build payjoin-cli
        run: cargo build -p payjoin-cli --manifest-path rust-payjoin/Cargo.toml

      - name: Set up BTCPay integration test environment
        uses: ./.github/actions/prepare-integration-test-env

      - name: Run Payjoin CLI integration tests
        run: dotnet test "BTCPayServer.Plugins.Payjoin.IntegrationTests/BTCPayServer.Plugins.Payjoin.IntegrationTests.csproj" -c Release --no-build --filter "FullyQualifiedName~BTCPayServer.Plugins.Payjoin.IntegrationTests.PayjoinCliIntegrationTests"

      - name: Dump BTCPay CLI integration test infrastructure logs on failure
        if: failure()
        run: docker compose -f btcpayserver/BTCPayServer.Tests/docker-compose.yml logs --no-color

      - name: Stop BTCPay CLI integration test infrastructure
        if: always()
        run: docker compose -f btcpayserver/BTCPayServer.Tests/docker-compose.yml down -v
